feat: automod
nextsnake/nextcore pull request #197
Opened 2023-02-19 13:07 UTC by MaskDuck

closes #154

2023-02-19 13:12 UTC, Lulalaby commented
Learn python lol

2023-02-19 13:22 UTC, Lulalaby commented
still wrong

2023-02-20 00:31 UTC, ooliver1 commented
Yes, you are wrong, shocking. Fix ya trailing whitespace, single quotes, type errors, lack of blank lines in wrappers :skull:

2023-03-12 10:45 UTC, TAG-Epic requested changes

2023-03-12 10:45 UTC, TAG-Epic commented on nextcore/http/client/wrappers/automod.py
> +            The priority of the request for the bucket rate-limiter.
You should not add the types. This is done automatically by sphinx.

2023-03-12 10:45 UTC, TAG-Epic commented on nextcore/http/client/wrappers/automod.py
> +        return await r.json()  # type: ignore [no-type-return]
Missing TODO comment about validating discords api

2023-03-12 10:45 UTC, TAG-Epic commented on nextcore/http/client/wrappers/automod.py
> +        headers = {"Authorization": str(authentication)}
Spacing here is not great. Please follow the style used by other wrappers

2023-03-12 10:45 UTC, TAG-Epic commented on nextcore/http/client/wrappers/automod.py
> +
Nitpick: remove this line?

2023-03-16 10:25 UTC, TAG-Epic commented
HTTP wrappers was removed in #201 so this is not needed. Thank you for the PR though!

2023-03-16 10:25 UTC, closed without merging